

CREATE QUERY tag_VIEW AS {
FROM LDBC_SNBI
MATCH (c:City {id: $cityId})
CREATE (p:Person {
    id: $personId,
    firstName: $personFirstName,
    lastName: $personLastName,
    gender: $gender,
    birthday: $birthday,
    creationDate: $creationDate,
    locationIP: $locationIP,
    browserUsed: $browserUsed,
    languages: $languages,
    email: $emails
  })-[:IS_LOCATED_IN]->(c)
RETURN  $tagIds AS tagId
}


Create Query as  interest_VIEW AS {
FROM tag_VIEW
  MATCH (t:Tag {id: tagId})
  CREATE (p)-[:HAS_INTEREST]->(t)
 Return p, count(*) AS times,
        $studyAt AS place
}

FROM interest_VIEW,LDBC_SNB
MATCH (o:Organisation {id: s[0]})
CREATE (p)-[:STUDY_AT {classYear: s[1]}]->(o)
Return p
      ,count(*) AS times2
      ,$workAt AS w
   
MATCH (comp:Organisation {id: w[0]})
  CREATE (p)-[:WORKS_AT {workFrom: w[1]}]->(comp)

