FROM LDBC_SNB
     MATCH (p:Person {id: $moderatorPersonId})
     CREATE (f:Forum {id: $forumId, title: $forumTitle, creationDate: $creationDate})-[:HAS_MODERATOR]->(p)
Return $tagIds AS tagId

FROM ...
MATCH (tag:Tag {id: tagId})
CREATE (f)-[:HAS_TAG]->(tag)

