SELECT f.id AS personId,f.firstName AS personFirstName,f.lastName AS personLastName,
        m.id AS postID,result AS postOrCommentContent,m.creationDate AS postDate
FROM LDBC_SNB
MATCH (P:Person {id: $personId })-[:KNOWS]-(f:Person)<-[:HAS_CREATOR]-(m:Message)
      WHERE message.creationDate <= $maxDate
      CASE : 
            m.content <> "" 
            THEN 
                    result = coalesce(m.content,m.imageFile) 
        
            ELSE   NULL
                    
        
            ORDER BY
                postOrCommentContent DESC,
                toInteger(postOrCommentId) ASC
            LIMIT 20
