//  QUERY tag_VIEW 
SELECT  $tagIds AS tagId
FROM LDBC_SNBI
     MATCH (c:City {id: $cityId})
     CREATE (p:Person {id: $personId,firstName: $personFirstName,lastName: $personLastName,gender: $gender,birthday: $birthday,creationDate: $creationDate,locationIP: $locationIP,
         browserUsed: $browserUsed,languages: $languages,email: $emails })-[:IS_LOCATED_IN]->(c)

//    interest_VIEW 
SELECT p, count(*) AS times,
FROM 
    MATCH (t:Tag {id: tagId})
    CREATE (p)-[:HAS_INTEREST]->(t)
        $studyAt AS place

SELECT p, count(*) AS times,$studyAt AS place
FROM 
    MATCH (t:Tag {id: tagId})
    CREATE (p)-[:HAS_INTEREST]->(t)


SELECT p,count(*) AS times2,$workAt AS w MATCH (comp:Organisation {id: w[0]})
FROM interest_VIEW,LDBC_SNB
     MATCH (o:Organisation {id: s[0]})
     CREATE (p)-[:STUDY_AT {classYear: s[1]}]->(o)
     CREATE (p)-[:WORKS_AT {workFrom: w[1]}]->(comp)

// ?? Can we construct it like this?  the workAt variable??

