SELECT c.id AS commentId,
       c.content AS content,
       c.creationDate AS creationDate,
       p.id AS AuthorId,
       p.firstName AS AuthorFirstName,
       p.lastName AS AuthorLastName,
CASE r:
     WHEN UKNOWN THEN false
    ELSE true
        END AS replyAuthorKnowsOriginalMessageAuthor
FROM LDBC_SNBI
MATCH (m:Message {id: $messageId })<-[:REPLY_OF]-(c:Comment)-[:HAS_CREATOR]->(p:Person)
OPTIONAL MATCH (m)-[:HAS_CREATOR]->(p2:Person)-[r:KNOWS]-(p1)
ORDER BY commentCreationDate DESC, AuthorId





