
//city1_VIEW
Select  person,countryX,countryY
FROM LDBC_SNB
MATCH (countryX:Country {name: $countryXName }),
      (countryY:Country {name: $countryYName }),
      (person:Person {id: $personId })
LIMIT 1

//  city2_VIEW 
SELECT  person,countryX,countryY,COLLECT(city) AS cities
FROM LDBC,country_VIEW
MATCH (city:City)-[:IS_PART_OF]->(country:Country)
WHERE country IN [countryX, countryY]


 // city3_VIEW 
SELECT  DISTINCT person2,countryX,countryY
FROM  LDBC_SNB,part_of_VIEW
MATCH (person)-[:KNOWS]{1,2}-(person2:person)-[:IS_LOCATED_IN]->(city)
WHERE person=person2 AND NOT city IN citiy

SELECT person2.id AS person2Id, person2.firstName AS person2FirstName
      ,person2.lastName AS person2LastName,sum(messageX) AS xCount
      ,sum(messageY) AS yCount,xCount + yCount AS xyCount
FROM LDBC_SNB,city1_VIEW,city2_VIEW,city3_VIEW
MATCH (person2)<-[:HAS_CREATOR]-(message),
      (message)-[:IS_LOCATED_IN]->(country)
WHERE $endDate > message.creationDate >= $startDate AND
      country IN [countryX, countryY]   
CASE WHEN country=countryX 
     THEN 1 
     ELSE 0 
     END AS messageX,
CASE WHEN country=countryY
     THEN 1 
     ELSE 0
     END AS messageY
WHERE xCount>0 AND yCount>0   
ORDER BY xyCount DESC, person2Id ASC
LIMIT 20

