// IS2. Recent messages of a person

//Query message_VIEW 
SELECT  message, message.id AS messageId, message.creationDate AS messageCreationDate
 FROM LDBC_SNB
     MATCH (:Person {id: $personId})<-[:HAS_CREATOR]-(:message)
ORDER BY messageCreationDate DESC, messageId ASC
LIMIT 10

SELECT  messageId,coalesce(message.imageFile,message.content) AS messageContent
        ,messageCreationDate,post.id AS postId,person.id AS personId,person.firstName AS FirstName,person.lastName AS LastName
From message_VIEW, LDBC_SNB
     MATCH (message)-[:REPLY_OF]->(post:Post)-[:HAS_CREATOR]->(person)
ORDER BY messageCreationDate DESC
        ,messageId ASC

