SELECT forum.title AS forumName,count(post) AS postCountpostCount
FROM INA
MATCH (p:Person { id: $personId })-[:KNOWS]-(friend:Person){1,1}
WHERE person <> f
MATCH (friend)<-[membership:HAS_MEMBER]-(forum),(friend)<-[:HAS_CREATOR]-(:Post)<-[:CONTAINER_OF]-(:Forum)
WHERE  membership.creationDate > $minDate
        AND    friend IN otherPersons // IN needs to be specified
ORDER BY
    postCount DESC,
    forum.id ASC
LIMIT 20

