
// Query tag_VIEW 
SELECT  knowTag.id as knownTagId
FROM LDBC_SNB
     MATCH (knowTag:Tag { name: $tagName })


// Query knowTag_VIEW 
SELECT knownTagId, (distinct f) as friends
FROM tag_VIEW
     MATCH (p:Person { id: $personId })-[:KNOWS]-(f: friend){1,2}
     WHERE  p<>f AND tag_VIEW.knownTagId == knownTagId

//final query
SELECT  t.name as nametag,count(post) as countPost
FROM tag_VIEW, knowTag_VIEW
MATCH (f)<-[:HAS_CREATOR]-(post:Post),
      (post)-[:HAS_TAG]->(t1:Tag{id: knownTagId}),
      (post)-[:HAS_TAG]->(t2:Tag)
WHERE  t1 <> t2      
ORDER BY
    nametag DESC,
    countPost ASC
LIMIT 10
