Select m.year as messageYear,
       mc as isComment, 
       lengthCategory,
       count(message) AS messageCount, 
       sum(message.length)/toFloat (count(message)) AS averageMessageLength, 
       sum(length) AS sumMessageLength, 
       messageCount / toFloat(totalMessageCountInt) AS percentageOfMessages
FROM BI
MATCH (m:Message),(mc:Comment)
WHERE message.creationDate < $datetime
AND  message.content IS NOT UNKNOWN  //Parser substitutes UNKNOWN instead of NULL
CASE 
WHEN m.length <  40 THEN 0 -- short
     WHEN m.length <  80 THEN 1 
     WHEN m.length < 160 THEN 2 
     ELSE  3 
   END AS lengthCategory

 GROUP BY messageYear, 
          isComment, 
          lengthCategory, 
 ORDER BY messageYear DESC, 
          isComment ASC,
          lengthCategory ASC