SELECT person1.id AS idPerson1
      ,person2.id AS idPerson2
      ,count(DISTINCT mutualFriend) AS mutualFriendCount
FROM  BI
MATCH (tag:Tag {name: $tag})<-[:HAS_INTEREST]-(person1:Person)-[:KNOWS]-(commonFriend:Person)-[:HAS_INTEREST]->(tag)
OPTIONAL MATCH (commonFriend:Person)-[:KNOWS]-(person2:Person), (person1)-[:!KNOWS]-(person2)
WHERE person1 <> person2
ORDER BY mutualFriendCount DESC
        ,person1Id ASC
        ,person2Id ASC
LIMIT 20
