SELECT rTag.name AS  rTag_name,
       count(*) AS count
FROM BI
MATCH  (tag:Tag {name:$tagname} )<-[:HAS_TAG]-(m:Message),
       (m)<-[:REPLY_OF]-(c:Comment)-[:HAS_TAG]->(rTag:Tag)

 GROUP BY  rTag_name
 ORDER BY count DESC
          ,rTag_name
LIMIT 100
EXCEPT ALL
SELECT tag1 as rTag_name
FROM BI
MATCH  (c1:Comment)~[:HAS_TAG]~(tag1:Tag) 

