FROM BI
MATCH  (tag:Tag {name:$tagname} )<-[:HAS_TAG]-(m:Message),
       (m)<-[:REPLY_OF]-(c:Comment)-[:HAS_TAG]->(rTag:Tag)
RETURN rTag.name AS  rTag_name,
       count(*) AS count
 GROUP BY  rTag_name
 ORDER BY count DESC
          ,rTag_name
LIMIT 100
EXECEPT ALL
FROM BI
MATCH  (c1:Comment)~[:HAS_TAG]~(tag1:Tag) 
Return rTag_name


