
/*Translation Bi9*/
FROM BI
MANDATORY MATCH (person:Person)<-[:HAS_CREATOR]-(post:Post)<-[:REPLY_OF]-(reply:Message)
WHERE  post.creationDate BETWEEN $startDate AND  $endDate
AND reply.creationDate BETWEEN $startDate AND $endDate
RETURN person_id ,person_firstName,person_lastName
      ,count(DISTINCT post) AS threadCount
      ,count(DISTINCT reply) AS messageCount
ORDER BY
  messageCount DESC,
  person.id ASC
LIMIT 100
